// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: proto/common/enums.proto

package common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Fuel int32

const (
	Fuel_FUEL_UNKNOWN Fuel = 0
	Fuel_GASOLINE     Fuel = 1
	Fuel_GAS          Fuel = 2
	Fuel_ELECTRICITY  Fuel = 3
)

// Enum value maps for Fuel.
var (
	Fuel_name = map[int32]string{
		0: "FUEL_UNKNOWN",
		1: "GASOLINE",
		2: "GAS",
		3: "ELECTRICITY",
	}
	Fuel_value = map[string]int32{
		"FUEL_UNKNOWN": 0,
		"GASOLINE":     1,
		"GAS":          2,
		"ELECTRICITY":  3,
	}
)

func (x Fuel) Enum() *Fuel {
	p := new(Fuel)
	*p = x
	return p
}

func (x Fuel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Fuel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_enums_proto_enumTypes[0].Descriptor()
}

func (Fuel) Type() protoreflect.EnumType {
	return &file_proto_common_enums_proto_enumTypes[0]
}

func (x Fuel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Fuel.Descriptor instead.
func (Fuel) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_enums_proto_rawDescGZIP(), []int{0}
}

type Category int32

const (
	Category_CATEGORY_UNKNOWN Category = 0
	Category_A1               Category = 1
	Category_A                Category = 2
	Category_B1               Category = 3
	Category_B                Category = 4
	Category_C1               Category = 5
	Category_C                Category = 6
	Category_D1               Category = 7
	Category_D                Category = 8
	Category_BE               Category = 9
	Category_C1E              Category = 10
	Category_CE               Category = 11
	Category_D1E              Category = 12
	Category_DE               Category = 13
	Category_T                Category = 14
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0:  "CATEGORY_UNKNOWN",
		1:  "A1",
		2:  "A",
		3:  "B1",
		4:  "B",
		5:  "C1",
		6:  "C",
		7:  "D1",
		8:  "D",
		9:  "BE",
		10: "C1E",
		11: "CE",
		12: "D1E",
		13: "DE",
		14: "T",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNKNOWN": 0,
		"A1":               1,
		"A":                2,
		"B1":               3,
		"B":                4,
		"C1":               5,
		"C":                6,
		"D1":               7,
		"D":                8,
		"BE":               9,
		"C1E":              10,
		"CE":               11,
		"D1E":              12,
		"DE":               13,
		"T":                14,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_enums_proto_enumTypes[1].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_proto_common_enums_proto_enumTypes[1]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_enums_proto_rawDescGZIP(), []int{1}
}

var File_proto_common_enums_proto protoreflect.FileDescriptor

var file_proto_common_enums_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2a, 0x40, 0x0a, 0x04, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x0c, 0x46, 0x55,
	0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x47, 0x41, 0x53, 0x4f, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x41,
	0x53, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x52, 0x49, 0x43, 0x49,
	0x54, 0x59, 0x10, 0x03, 0x2a, 0x8d, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x31, 0x10, 0x01, 0x12,
	0x05, 0x0a, 0x01, 0x41, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x42, 0x31, 0x10, 0x03, 0x12, 0x05,
	0x0a, 0x01, 0x42, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x43, 0x31, 0x10, 0x05, 0x12, 0x05, 0x0a,
	0x01, 0x43, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x31, 0x10, 0x07, 0x12, 0x05, 0x0a, 0x01,
	0x44, 0x10, 0x08, 0x12, 0x06, 0x0a, 0x02, 0x42, 0x45, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x31, 0x45, 0x10, 0x0a, 0x12, 0x06, 0x0a, 0x02, 0x43, 0x45, 0x10, 0x0b, 0x12, 0x07, 0x0a, 0x03,
	0x44, 0x31, 0x45, 0x10, 0x0c, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x45, 0x10, 0x0d, 0x12, 0x05, 0x0a,
	0x01, 0x54, 0x10, 0x0e, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_common_enums_proto_rawDescOnce sync.Once
	file_proto_common_enums_proto_rawDescData = file_proto_common_enums_proto_rawDesc
)

func file_proto_common_enums_proto_rawDescGZIP() []byte {
	file_proto_common_enums_proto_rawDescOnce.Do(func() {
		file_proto_common_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_enums_proto_rawDescData)
	})
	return file_proto_common_enums_proto_rawDescData
}

var file_proto_common_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_enums_proto_goTypes = []interface{}{
	(Fuel)(0),     // 0: common.Fuel
	(Category)(0), // 1: common.Category
}
var file_proto_common_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_enums_proto_init() }
func file_proto_common_enums_proto_init() {
	if File_proto_common_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_enums_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_enums_proto_goTypes,
		DependencyIndexes: file_proto_common_enums_proto_depIdxs,
		EnumInfos:         file_proto_common_enums_proto_enumTypes,
	}.Build()
	File_proto_common_enums_proto = out.File
	file_proto_common_enums_proto_rawDesc = nil
	file_proto_common_enums_proto_goTypes = nil
	file_proto_common_enums_proto_depIdxs = nil
}
