// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: proto/core/customer.proto

package core

import (
	common "github.com/opencars/grpc/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberRequestByCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *NumberRequestByCustomer) Reset() {
	*x = NumberRequestByCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_core_customer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberRequestByCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequestByCustomer) ProtoMessage() {}

func (x *NumberRequestByCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_customer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequestByCustomer.ProtoReflect.Descriptor instead.
func (*NumberRequestByCustomer) Descriptor() ([]byte, []int) {
	return file_proto_core_customer_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequestByCustomer) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type VINRequestByCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin string `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *VINRequestByCustomer) Reset() {
	*x = VINRequestByCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_core_customer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VINRequestByCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VINRequestByCustomer) ProtoMessage() {}

func (x *VINRequestByCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_customer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VINRequestByCustomer.ProtoReflect.Descriptor instead.
func (*VINRequestByCustomer) Descriptor() ([]byte, []int) {
	return file_proto_core_customer_proto_rawDescGZIP(), []int{1}
}

func (x *VINRequestByCustomer) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type ResultForCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicles []*ResultForCustomer_Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
}

func (x *ResultForCustomer) Reset() {
	*x = ResultForCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_core_customer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultForCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultForCustomer) ProtoMessage() {}

func (x *ResultForCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_customer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultForCustomer.ProtoReflect.Descriptor instead.
func (*ResultForCustomer) Descriptor() ([]byte, []int) {
	return file_proto_core_customer_proto_rawDescGZIP(), []int{2}
}

func (x *ResultForCustomer) GetVehicles() []*ResultForCustomer_Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type ResultForCustomer_Vehicle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin          string       `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	FirstRegDate *common.Date `protobuf:"bytes,2,opt,name=first_reg_date,json=firstRegDate,proto3" json:"first_reg_date,omitempty"`
	Brand        string       `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model        string       `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year         int32        `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Actions      []*Action    `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *ResultForCustomer_Vehicle) Reset() {
	*x = ResultForCustomer_Vehicle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_core_customer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultForCustomer_Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultForCustomer_Vehicle) ProtoMessage() {}

func (x *ResultForCustomer_Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_customer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultForCustomer_Vehicle.ProtoReflect.Descriptor instead.
func (*ResultForCustomer_Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_core_customer_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ResultForCustomer_Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *ResultForCustomer_Vehicle) GetFirstRegDate() *common.Date {
	if x != nil {
		return x.FirstRegDate
	}
	return nil
}

func (x *ResultForCustomer_Vehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ResultForCustomer_Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ResultForCustomer_Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ResultForCustomer_Vehicle) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_proto_core_customer_proto protoreflect.FileDescriptor

var file_proto_core_customer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72,
	0x65, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x17, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x14, 0x56, 0x49, 0x4e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x6e,
	0x22, 0x8a, 0x02, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x1a, 0xb7, 0x01, 0x0a, 0x07, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x69,
	0x6e, 0x12, 0x32, 0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65,
	0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x26, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x9f, 0x01,
	0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x48, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x46, 0x6f,
	0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x56, 0x49, 0x4e, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x56, 0x49, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x00, 0x42,
	0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_core_customer_proto_rawDescOnce sync.Once
	file_proto_core_customer_proto_rawDescData = file_proto_core_customer_proto_rawDesc
)

func file_proto_core_customer_proto_rawDescGZIP() []byte {
	file_proto_core_customer_proto_rawDescOnce.Do(func() {
		file_proto_core_customer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_core_customer_proto_rawDescData)
	})
	return file_proto_core_customer_proto_rawDescData
}

var file_proto_core_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_core_customer_proto_goTypes = []interface{}{
	(*NumberRequestByCustomer)(nil),   // 0: core.NumberRequestByCustomer
	(*VINRequestByCustomer)(nil),      // 1: core.VINRequestByCustomer
	(*ResultForCustomer)(nil),         // 2: core.ResultForCustomer
	(*ResultForCustomer_Vehicle)(nil), // 3: core.ResultForCustomer.Vehicle
	(*common.Date)(nil),               // 4: common.Date
	(*Action)(nil),                    // 5: core.Action
}
var file_proto_core_customer_proto_depIdxs = []int32{
	3, // 0: core.ResultForCustomer.vehicles:type_name -> core.ResultForCustomer.Vehicle
	4, // 1: core.ResultForCustomer.Vehicle.first_reg_date:type_name -> common.Date
	5, // 2: core.ResultForCustomer.Vehicle.actions:type_name -> core.Action
	0, // 3: core.CustomerService.FindByNumber:input_type -> core.NumberRequestByCustomer
	1, // 4: core.CustomerService.FindByVIN:input_type -> core.VINRequestByCustomer
	2, // 5: core.CustomerService.FindByNumber:output_type -> core.ResultForCustomer
	2, // 6: core.CustomerService.FindByVIN:output_type -> core.ResultForCustomer
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_core_customer_proto_init() }
func file_proto_core_customer_proto_init() {
	if File_proto_core_customer_proto != nil {
		return
	}
	file_proto_core_action_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_core_customer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberRequestByCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_core_customer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VINRequestByCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_core_customer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultForCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_core_customer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultForCustomer_Vehicle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_core_customer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_customer_proto_goTypes,
		DependencyIndexes: file_proto_core_customer_proto_depIdxs,
		MessageInfos:      file_proto_core_customer_proto_msgTypes,
	}.Build()
	File_proto_core_customer_proto = out.File
	file_proto_core_customer_proto_rawDesc = nil
	file_proto_core_customer_proto_goTypes = nil
	file_proto_core_customer_proto_depIdxs = nil
}
