// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: koatuu/v1/koatuu.proto

package koatuuv1

import (
	v1 "github.com/opencars/grpc/pkg/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koatuu_v1_koatuu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koatuu_v1_koatuu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_koatuu_v1_koatuu_proto_rawDescGZIP(), []int{0}
}

func (x *DecodeRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type DecodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*DecodeResultItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *DecodeResponse) Reset() {
	*x = DecodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koatuu_v1_koatuu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponse) ProtoMessage() {}

func (x *DecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koatuu_v1_koatuu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponse.ProtoReflect.Descriptor instead.
func (*DecodeResponse) Descriptor() ([]byte, []int) {
	return file_koatuu_v1_koatuu_proto_rawDescGZIP(), []int{1}
}

func (x *DecodeResponse) GetItems() []*DecodeResultItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DecodeResultItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary string    `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Parts   []string  `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	Error   *v1.Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DecodeResultItem) Reset() {
	*x = DecodeResultItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_koatuu_v1_koatuu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecodeResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResultItem) ProtoMessage() {}

func (x *DecodeResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_koatuu_v1_koatuu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResultItem.ProtoReflect.Descriptor instead.
func (*DecodeResultItem) Descriptor() ([]byte, []int) {
	return file_koatuu_v1_koatuu_proto_rawDescGZIP(), []int{2}
}

func (x *DecodeResultItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DecodeResultItem) GetParts() []string {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *DecodeResultItem) GetError() *v1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_koatuu_v1_koatuu_proto protoreflect.FileDescriptor

var file_koatuu_v1_koatuu_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x6f, 0x61, 0x74,
	0x75, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75,
	0x2e, 0x76, 0x31, 0x1a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0d, 0x44, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x43, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x48, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a,
	0x06, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x2e, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x92, 0x01, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x2e, 0x76, 0x31, 0x42, 0x0b,
	0x4b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x61,
	0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x6f, 0x61, 0x74,
	0x75, 0x75, 0x2f, 0x76, 0x31, 0x3b, 0x6b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x4b, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x4b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x09, 0x4b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x4b,
	0x6f, 0x61, 0x74, 0x75, 0x75, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x4b, 0x6f, 0x61, 0x74, 0x75, 0x75, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_koatuu_v1_koatuu_proto_rawDescOnce sync.Once
	file_koatuu_v1_koatuu_proto_rawDescData = file_koatuu_v1_koatuu_proto_rawDesc
)

func file_koatuu_v1_koatuu_proto_rawDescGZIP() []byte {
	file_koatuu_v1_koatuu_proto_rawDescOnce.Do(func() {
		file_koatuu_v1_koatuu_proto_rawDescData = protoimpl.X.CompressGZIP(file_koatuu_v1_koatuu_proto_rawDescData)
	})
	return file_koatuu_v1_koatuu_proto_rawDescData
}

var file_koatuu_v1_koatuu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_koatuu_v1_koatuu_proto_goTypes = []interface{}{
	(*DecodeRequest)(nil),    // 0: koatuu.v1.DecodeRequest
	(*DecodeResponse)(nil),   // 1: koatuu.v1.DecodeResponse
	(*DecodeResultItem)(nil), // 2: koatuu.v1.DecodeResultItem
	(*v1.Error)(nil),         // 3: common.v1.Error
}
var file_koatuu_v1_koatuu_proto_depIdxs = []int32{
	2, // 0: koatuu.v1.DecodeResponse.items:type_name -> koatuu.v1.DecodeResultItem
	3, // 1: koatuu.v1.DecodeResultItem.error:type_name -> common.v1.Error
	0, // 2: koatuu.v1.Service.Decode:input_type -> koatuu.v1.DecodeRequest
	1, // 3: koatuu.v1.Service.Decode:output_type -> koatuu.v1.DecodeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_koatuu_v1_koatuu_proto_init() }
func file_koatuu_v1_koatuu_proto_init() {
	if File_koatuu_v1_koatuu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_koatuu_v1_koatuu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koatuu_v1_koatuu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_koatuu_v1_koatuu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecodeResultItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_koatuu_v1_koatuu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koatuu_v1_koatuu_proto_goTypes,
		DependencyIndexes: file_koatuu_v1_koatuu_proto_depIdxs,
		MessageInfos:      file_koatuu_v1_koatuu_proto_msgTypes,
	}.Build()
	File_koatuu_v1_koatuu_proto = out.File
	file_koatuu_v1_koatuu_proto_rawDesc = nil
	file_koatuu_v1_koatuu_proto_goTypes = nil
	file_koatuu_v1_koatuu_proto_depIdxs = nil
}
