// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: proto/wanted/wanted.proto

package wanted

import (
	common "github.com/opencars/grpc/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle_Status int32

const (
	Vehicle_STATUS_UNKNOWN Vehicle_Status = 0
	Vehicle_STATUS_STOLEN  Vehicle_Status = 1
	Vehicle_STATUS_REMOVED Vehicle_Status = 2
)

// Enum value maps for Vehicle_Status.
var (
	Vehicle_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_STOLEN",
		2: "STATUS_REMOVED",
	}
	Vehicle_Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_STOLEN":  1,
		"STATUS_REMOVED": 2,
	}
)

func (x Vehicle_Status) Enum() *Vehicle_Status {
	p := new(Vehicle_Status)
	*p = x
	return p
}

func (x Vehicle_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vehicle_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wanted_wanted_proto_enumTypes[0].Descriptor()
}

func (Vehicle_Status) Type() protoreflect.EnumType {
	return &file_proto_wanted_wanted_proto_enumTypes[0]
}

func (x Vehicle_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vehicle_Status.Descriptor instead.
func (Vehicle_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_wanted_wanted_proto_rawDescGZIP(), []int{2, 0}
}

type FindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number []string `protobuf:"bytes,1,rep,name=number,proto3" json:"number,omitempty"`
	Vin    []string `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wanted_wanted_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wanted_wanted_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_proto_wanted_wanted_proto_rawDescGZIP(), []int{0}
}

func (x *FindRequest) GetNumber() []string {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *FindRequest) GetVin() []string {
	if x != nil {
		return x.Vin
	}
	return nil
}

type FindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicles []*Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wanted_wanted_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wanted_wanted_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_proto_wanted_wanted_proto_rawDescGZIP(), []int{1}
}

func (x *FindResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type Vehicle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Brand         string         `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string         `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Color         string         `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Number        string         `protobuf:"bytes,6,opt,name=number,proto3" json:"number,omitempty"`
	BodyNumber    string         `protobuf:"bytes,7,opt,name=body_number,json=bodyNumber,proto3" json:"body_number,omitempty"`
	ChassisNumber string         `protobuf:"bytes,8,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	EngineNumber  string         `protobuf:"bytes,9,opt,name=engine_number,json=engineNumber,proto3" json:"engine_number,omitempty"`
	Ovd           string         `protobuf:"bytes,10,opt,name=ovd,proto3" json:"ovd,omitempty"`
	Kind          string         `protobuf:"bytes,11,opt,name=kind,proto3" json:"kind,omitempty"`
	Status        Vehicle_Status `protobuf:"varint,12,opt,name=status,proto3,enum=wanted.Vehicle_Status" json:"status,omitempty"`
	RevisionId    string         `protobuf:"bytes,13,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	TheftDate     *common.Date   `protobuf:"bytes,14,opt,name=theft_date,json=theftDate,proto3" json:"theft_date,omitempty"`
	InsertDate    *common.Date   `protobuf:"bytes,15,opt,name=insert_date,json=insertDate,proto3" json:"insert_date,omitempty"`
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wanted_wanted_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wanted_wanted_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_wanted_wanted_proto_rawDescGZIP(), []int{2}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Vehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Vehicle) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Vehicle) GetBodyNumber() string {
	if x != nil {
		return x.BodyNumber
	}
	return ""
}

func (x *Vehicle) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *Vehicle) GetEngineNumber() string {
	if x != nil {
		return x.EngineNumber
	}
	return ""
}

func (x *Vehicle) GetOvd() string {
	if x != nil {
		return x.Ovd
	}
	return ""
}

func (x *Vehicle) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Vehicle) GetStatus() Vehicle_Status {
	if x != nil {
		return x.Status
	}
	return Vehicle_STATUS_UNKNOWN
}

func (x *Vehicle) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *Vehicle) GetTheftDate() *common.Date {
	if x != nil {
		return x.TheftDate
	}
	return nil
}

func (x *Vehicle) GetInsertDate() *common.Date {
	if x != nil {
		return x.InsertDate
	}
	return nil
}

var File_proto_wanted_wanted_proto protoreflect.FileDescriptor

var file_proto_wanted_wanted_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x2f, 0x77,
	0x61, 0x6e, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x61, 0x6e,
	0x74, 0x65, 0x64, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0b,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x76, 0x69, 0x6e, 0x22, 0x3b, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64,
	0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x22, 0x8e, 0x04, 0x0a, 0x07, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x73, 0x73, 0x69, 0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x73, 0x73, 0x69, 0x73,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6f,
	0x76, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x76, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x2b, 0x0a, 0x0a, 0x74, 0x68, 0x65, 0x66, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x44, 0x61, 0x74, 0x65, 0x52, 0x09, 0x74, 0x68, 0x65, 0x66, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x2d, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0x43,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x4c, 0x45, 0x4e, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45,
	0x44, 0x10, 0x02, 0x32, 0x3c, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31,
	0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12, 0x13, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x77, 0x61,
	0x6e, 0x74, 0x65, 0x64, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x70, 0x65, 0x6e, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x77, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_wanted_wanted_proto_rawDescOnce sync.Once
	file_proto_wanted_wanted_proto_rawDescData = file_proto_wanted_wanted_proto_rawDesc
)

func file_proto_wanted_wanted_proto_rawDescGZIP() []byte {
	file_proto_wanted_wanted_proto_rawDescOnce.Do(func() {
		file_proto_wanted_wanted_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wanted_wanted_proto_rawDescData)
	})
	return file_proto_wanted_wanted_proto_rawDescData
}

var file_proto_wanted_wanted_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wanted_wanted_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wanted_wanted_proto_goTypes = []interface{}{
	(Vehicle_Status)(0),  // 0: wanted.Vehicle.Status
	(*FindRequest)(nil),  // 1: wanted.FindRequest
	(*FindResponse)(nil), // 2: wanted.FindResponse
	(*Vehicle)(nil),      // 3: wanted.Vehicle
	(*common.Date)(nil),  // 4: common.Date
}
var file_proto_wanted_wanted_proto_depIdxs = []int32{
	3, // 0: wanted.FindResponse.vehicles:type_name -> wanted.Vehicle
	0, // 1: wanted.Vehicle.status:type_name -> wanted.Vehicle.Status
	4, // 2: wanted.Vehicle.theft_date:type_name -> common.Date
	4, // 3: wanted.Vehicle.insert_date:type_name -> common.Date
	1, // 4: wanted.Service.Find:input_type -> wanted.FindRequest
	2, // 5: wanted.Service.Find:output_type -> wanted.FindResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_wanted_wanted_proto_init() }
func file_proto_wanted_wanted_proto_init() {
	if File_proto_wanted_wanted_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wanted_wanted_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wanted_wanted_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wanted_wanted_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vehicle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wanted_wanted_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wanted_wanted_proto_goTypes,
		DependencyIndexes: file_proto_wanted_wanted_proto_depIdxs,
		EnumInfos:         file_proto_wanted_wanted_proto_enumTypes,
		MessageInfos:      file_proto_wanted_wanted_proto_msgTypes,
	}.Build()
	File_proto_wanted_wanted_proto = out.File
	file_proto_wanted_wanted_proto_rawDesc = nil
	file_proto_wanted_wanted_proto_goTypes = nil
	file_proto_wanted_wanted_proto_depIdxs = nil
}
